[package]
name = "fractal"
version = "0.1.0"
authors = ["Jake Herman <jakeherman3@gmail.com>"]

[dependencies]
glium = "0.20.0"
rand = "0.4.2"
imgui = { git = "https://github.com/Gekkio/imgui-rs" }
imgui-glium-renderer = { git = "https://github.com/Gekkio/imgui-rs" }
